version: 2
jobs:
  build:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run:
          name: pre 
          command: apt-get update && apt-get install -y autoconf automake libtool autoconf make gcc python-sphinx
      - run:
          name: bootstrap
          command: ./bootstrap.sh
      - run:
          name: autoconf
          command: ./configure
      - run:
          name: build
          command: make 
      - run:
          name: build docs
          command: cd docs; make html; cd -
      - run:
          name: install
          command: make install

